theme: jekyll-theme-leap-day
slack-workspace: codefellows
instructor-feedback-url: mailto:instructor-feedback@codefellows.com?subject=Instructional%20feedback
description: Guia de configuraci√≥n - Enter Tech School
